import { useState } from "react"
import { Calendar, Clock, DollarSign, User, AlertCircle, Plus, Minus } from "lucide-react"
import { Button } from "./ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card"
import { Input } from "./ui/input"
import { Label } from "./ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select"
import { Checkbox } from "./ui/checkbox"
import { useWallet } from "./wallet-provider"
import { useToast } from "../hooks/use-toast"
