import { useState, useEffect } from "react"
import { Search, Filter, Clock, ExternalLink, Eye } from "lucide-react"
import { Button } from "./ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card"
import { Input } from "./ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select"
import { Badge } from "./ui/badge"
import { useWallet } from "./wallet-provider"
import { useToast } from "../hooks/use-toast"
import { LockDetailDrawer } from "./lock-detail-drawer"
import { MobileLockCard } from "./mobile-lock-card"
import { useIsMobile } from "../hooks/use-mobile"
